local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
host    all             all             172.16.0.0/12           scram-sha-256
host    replication     replicator      10.8.0.2/32             scram-sha-256
host    all             whydud          10.8.0.2/32             scram-sha-256
host    all             whydud          10.8.0.3/32             scram-sha-256
host    all             whydud          10.8.0.4/32             scram-sha-256
