# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('in_stock', models.BooleanField(null=True)),
                ('seller_name', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'price_snapshots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=20)),
                ('offer_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bank_slug', models.CharField(blank=True, max_length=50)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('card_network', models.CharField(blank=True, max_length=20)),
                ('card_variants', models.JSONField(default=list)),
                ('wallet_provider', models.CharField(blank=True, max_length=50)),
                ('membership_type', models.CharField(blank=True, max_length=50)),
                ('coupon_code', models.CharField(blank=True, max_length=100)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Off'), ('percent', 'Percent Off'), ('cashback', 'Cashback'), ('no_cost_emi', 'No Cost EMI')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi_tenures', models.JSONField(default=list)),
                ('emi_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emi_processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stackable', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=30)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productlisting')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marketplace')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'marketplace_offers',
                'indexes': [models.Index(fields=['marketplace', 'is_active'], name='marketplace_marketp_6df80b_idx'), models.Index(fields=['bank_slug'], name='marketplace_bank_sl_d196bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
