# Generated by Django 5.2.11 on 2026-02-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_timescaledb_setup'),
        ('products', '0002_seed_marketplaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_page', models.CharField(max_length=50)),
                ('source_section', models.CharField(blank=True, max_length=50)),
                ('affiliate_url', models.URLField(max_length=2000)),
                ('affiliate_tag', models.CharField(blank=True, max_length=100)),
                ('sub_tag', models.CharField(blank=True, max_length=200)),
                ('purchase_confirmed', models.BooleanField(default=False)),
                ('confirmation_source', models.CharField(blank=True, max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('price_at_click', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='products.productlisting')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='products.marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'click_events',
                'indexes': [models.Index(fields=['user', '-clicked_at'], name='click_event_user_id_df9c2b_idx'), models.Index(fields=['product', '-clicked_at'], name='click_event_product_1e82f6_idx')],
            },
        ),
    ]
