# Generated by Django 5.2.11 on 2026-02-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_clickevent'),
        ('products', '0002_seed_marketplaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Drop old unique_together (user, product) before schema changes
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together=set(),
        ),
        # 2. Move table to users schema via raw SQL (AlterModelTable can't cross schemas)
        migrations.RunSQL(
            sql='ALTER TABLE "price_alerts" SET SCHEMA "users";',
            reverse_sql='ALTER TABLE "users"."price_alerts" SET SCHEMA "public";',
            state_operations=[
                migrations.AlterModelTable(
                    name='pricealert',
                    table='users"."price_alerts',
                ),
            ],
        ),
        # 3. Add all new fields
        migrations.AddField(
            model_name='pricealert',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.marketplace'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_marketplace',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # 4. Set new unique_together AFTER marketplace field exists
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('user', 'product', 'marketplace')},
        ),
        # 5. Add indexes and remove old field
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active', 'product'], name='idx_alerts_active'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active'], name='price_alert_user_id_600b95_idx'),
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='last_alerted_at',
        ),
    ]
