# Generated by Django 5.2.11 on 2026-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_backfillproduct_scrape_status'),
        ('products', '0006_add_is_lightweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesnapshot',
            options={'managed': False, 'ordering': ['-time']},
        ),
        migrations.RenameIndex(
            model_name='backfillproduct',
            new_name='backfill_pr_status_1c990e_idx',
            old_name='pricing_back_status_3c9a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='backfillproduct',
            new_name='backfill_pr_externa_e0908d_idx',
            old_name='pricing_back_externa_f5c1d8_idx',
        ),
        migrations.AddField(
            model_name='backfillproduct',
            name='enrichment_method',
            field=models.CharField(choices=[('pending', 'Pending'), ('playwright', 'Playwright'), ('curl_cffi', 'curl_cffi'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='backfillproduct',
            name='enrichment_priority',
            field=models.SmallIntegerField(db_index=True, default=3, help_text='0=on-demand, 1=Playwright, 2=curl_cffi, 3=curl_cffi-low'),
        ),
        migrations.AddField(
            model_name='backfillproduct',
            name='enrichment_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backfillproduct',
            name='review_count_scraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backfillproduct',
            name='review_status',
            field=models.CharField(choices=[('skip', 'Skip'), ('pending', 'Pending'), ('scraping', 'Scraping'), ('scraped', 'Scraped'), ('failed', 'Failed')], default='skip', help_text='Review scraping status — only top 100K get reviews', max_length=20),
        ),
        migrations.AlterField(
            model_name='backfillproduct',
            name='scrape_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enriching', 'Enriching'), ('scraped', 'Scraped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='backfillproduct',
            index=models.Index(fields=['scrape_status', 'enrichment_priority', 'created_at'], name='idx_backfill_enrich_queue'),
        ),
        migrations.AddIndex(
            model_name='backfillproduct',
            index=models.Index(fields=['review_status', 'scrape_status'], name='idx_backfill_review_queue'),
        ),
    ]
