# Generated by Django 5.2.11 on 2026-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DudScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('config_version', models.IntegerField()),
                ('component_scores', models.JSONField()),
            ],
            options={
                'db_table': 'scoring"."dudscore_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DudScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('w_sentiment', models.DecimalField(decimal_places=3, max_digits=4)),
                ('w_rating_quality', models.DecimalField(decimal_places=3, max_digits=4)),
                ('w_price_value', models.DecimalField(decimal_places=3, max_digits=4)),
                ('w_review_credibility', models.DecimalField(decimal_places=3, max_digits=4)),
                ('w_price_stability', models.DecimalField(decimal_places=3, max_digits=4)),
                ('w_return_signal', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fraud_penalty_threshold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('min_review_threshold', models.IntegerField()),
                ('cold_start_penalty', models.DecimalField(decimal_places=2, max_digits=3)),
                ('anomaly_spike_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('change_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring"."dudscore_config',
            },
        ),
    ]
