# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_slug', models.CharField(max_length=100, unique=True)),
                ('brand_logo_url', models.URLField(blank=True, max_length=500)),
                ('denominations', models.JSONField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('fulfillment_partner', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users"."gift_card_catalog',
            },
        ),
        migrations.CreateModel(
            name='RewardBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reward_balance', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('total_expired', models.IntegerField(default=0)),
                ('current_balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users"."reward_balances',
            },
        ),
        migrations.CreateModel(
            name='GiftCardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=12)),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('gift_card_code', models.TextField(blank=True)),
                ('delivery_email', models.EmailField(blank=True, max_length=320)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rewards.giftcardcatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."gift_card_redemptions',
            },
        ),
        migrations.CreateModel(
            name='RewardPointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('action_type', models.CharField(max_length=50)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."reward_points_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
