"""Amazon.in review spider — scrapes customer reviews for existing product listings.

Scrapes "Top Reviews" from the product detail page (/dp/<ASIN>).  Amazon's
dedicated review pages (/product-reviews/<ASIN>/) require sign-in, so we
extract the ~8 reviews embedded on each product page instead.

Only scrapes products that already have a ProductListing in our DB with fewer
than 10 scraped reviews — avoids re-scraping well-covered products.

Sprint 2.
"""
import random

import scrapy
from scrapy_playwright.page import PageMethod

from apps.scraping.items import ReviewItem
from .base_spider import BaseWhydudSpider

MARKETPLACE_SLUG = "amazon-in"


class AmazonReviewSpider(BaseWhydudSpider):
    """Scrapes Amazon.in customer reviews from product detail pages.

    Uses Playwright — review content is JS-rendered on /dp/ pages.
    CAPTCHA pages are skipped (reviews are lower priority than products).

    Spider arguments (passed via ``-a``):
      max_review_pages — ignored (product pages have no review pagination).
    """

    name = "amazon_in_reviews"
    allowed_domains = ["amazon.in", "www.amazon.in"]

    # No custom_settings override needed — base spider + scrapy_settings.py
    # already provide DOWNLOAD_HANDLERS, ROBOTSTXT_OBEY: False, and delays.

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.max_review_pages = int(kwargs.get("max_review_pages", 1))

        # Stats
        self._reviews_scraped: int = 0
        self._captcha_skipped: int = 0
        self._products_processed: int = 0

    # ------------------------------------------------------------------
    # Stealth
    # ------------------------------------------------------------------

    async def _apply_stealth(self, page, request):
        """Apply playwright-stealth scripts to a page before navigation."""
        await self.STEALTH.apply_stealth_async(page)

    # ------------------------------------------------------------------
    # CAPTCHA detection
    # ------------------------------------------------------------------

    def _is_captcha_page(self, response) -> bool:
        """Detect if Amazon served a CAPTCHA / bot-check page."""
        page_title = (response.css("title::text").get() or "").strip().lower()
        if page_title in ("amazon.in", "robot check", ""):
            return True
        if response.css("form[action*='validateCaptcha']"):
            return True
        if b"captcha" in response.body[:5000].lower():
            return True
        return False

    # ------------------------------------------------------------------
    # start_requests
    # ------------------------------------------------------------------

    def start_requests(self):
        """Get all Amazon ProductListings that have fewer than 10 reviews in our DB."""
        from django.db.models import Count, Q

        from apps.products.models import ProductListing

        listings = (
            ProductListing.objects.filter(
                marketplace__slug="amazon-in",
                in_stock=True,
            )
            .annotate(
                db_review_count=Count(
                    "product__reviews",
                    filter=Q(product__reviews__marketplace__slug="amazon-in"),
                )
            )
            .filter(db_review_count__lt=10)
            .order_by("-product__total_reviews")[:200]
        )

        for listing in listings:
            asin = listing.external_id
            # Skip synthetic ASINs (generated by seed data, not real Amazon IDs)
            if asin.startswith(("amazon_in_", "amazon-in_")) or len(asin) > 12:
                continue
            # Use product detail page — review pages require sign-in
            url = f"https://www.amazon.in/dp/{asin}"
            yield scrapy.Request(
                url,
                callback=self.parse_product_reviews,
                errback=self.handle_error,
                meta={
                    "asin": asin,
                    "playwright": True,
                    "playwright_page_init_callback": self._apply_stealth,
                    "playwright_page_methods": [
                        PageMethod("wait_for_load_state", "domcontentloaded"),
                        PageMethod("wait_for_timeout", random.randint(2000, 4000)),
                    ],
                },
                headers=self._make_headers(),
            )

    # ------------------------------------------------------------------
    # Review parsing from product detail page
    # ------------------------------------------------------------------

    def parse_product_reviews(self, response):
        """Parse reviews embedded on an Amazon.in product detail page."""
        asin = response.meta["asin"]
        self._products_processed += 1

        # CAPTCHA detection — skip this product's reviews (don't retry)
        if self._is_captcha_page(response):
            self._captcha_skipped += 1
            self.logger.info(
                f"CAPTCHA on review page for ASIN {asin} — skipping (reviews are lower priority)"
            )
            return

        # Reviews are <li> elements with data-hook="review" (not <div>)
        reviews = response.css('[data-hook="review"]')
        if not reviews:
            reviews = response.css("li.review")
        if not reviews:
            reviews = response.css("div.review")

        self.logger.info(
            f"Found {len(reviews)} reviews on product page for ASIN {asin}"
        )

        for review_el in reviews:
            item = ReviewItem()
            item["marketplace_slug"] = MARKETPLACE_SLUG
            item["product_external_id"] = asin

            # Review ID — the element's id attribute (e.g., "R35S93KNX92YP9")
            review_id = review_el.attrib.get("id", "")
            item["review_id"] = review_id

            # Rating (1-5)
            rating_text = review_el.css(
                'i[data-hook="review-star-rating"] span.a-icon-alt::text'
            ).get("")
            if not rating_text:
                rating_text = review_el.css(
                    "i.review-rating span.a-icon-alt::text"
                ).get("")
            if not rating_text:
                rating_text = review_el.css(
                    "span.a-icon-alt::text"
                ).get("")
            try:
                item["rating"] = int(float(rating_text.split(" ")[0]))
            except (ValueError, IndexError):
                item["rating"] = None

            # Title — on product pages, title is inside [data-hook="review-title"]
            # Spans: [a-icon-alt (rating)] [a-letter-space] [actual title]
            title_spans = review_el.css(
                '[data-hook="review-title"] span:not(.a-icon-alt):not(.a-letter-space)::text'
            ).getall()
            item["title"] = " ".join(t.strip() for t in title_spans if t.strip())
            if not item["title"]:
                # Fallback: try <a> tag variant (used on dedicated review pages)
                item["title"] = (
                    review_el.css('a[data-hook="review-title"] span::text').get("").strip()
                )

            # Body
            body_parts = review_el.css(
                'span[data-hook="review-body"] span::text'
            ).getall()
            item["body"] = " ".join(t.strip() for t in body_parts if t.strip())
            if not item["body"]:
                item["body"] = (
                    review_el.css('[data-hook="review-body"]::text').get("").strip()
                )

            # Reviewer name
            item["reviewer_name"] = (
                review_el.css("span.a-profile-name::text").get("").strip()
            )

            # Reviewer ID (from profile link)
            profile_link = review_el.css("a.a-profile::attr(href)").get("")
            if "/profile/" in profile_link:
                item["reviewer_id"] = (
                    profile_link.split("/profile/")[-1].split("/")[0].split("?")[0]
                )

            # Date — "Reviewed in India on 15 January 2026"
            date_text = review_el.css(
                'span[data-hook="review-date"]::text'
            ).get("")
            if " on " in date_text:
                date_str = date_text.split(" on ")[-1].strip()
                item["review_date"] = date_str

            # Country
            if "in India" in date_text:
                item["country"] = "India"

            # Verified purchase — check both data-hook badge and full text
            verified = review_el.css(
                'span[data-hook="avp-badge"]::text'
            ).get("")
            if not verified:
                # On product pages, "Verified Purchase" may appear as plain text
                all_text = " ".join(review_el.css("::text").getall())
                item["is_verified_purchase"] = "Verified Purchase" in all_text
            else:
                item["is_verified_purchase"] = "Verified Purchase" in verified

            # Helpful votes — "234 people found this helpful" / "One person …"
            helpful_text = review_el.css(
                'span[data-hook="helpful-vote-statement"]::text'
            ).get("")
            if helpful_text:
                helpful_text = helpful_text.strip().lower()
                if helpful_text.startswith("one"):
                    item["helpful_votes"] = 1
                else:
                    try:
                        item["helpful_votes"] = int(
                            helpful_text.split(" ")[0].replace(",", "")
                        )
                    except ValueError:
                        item["helpful_votes"] = 0
            else:
                item["helpful_votes"] = 0

            # Images — upgrade thumbnail to full size
            images = review_el.css(
                'img[data-hook="review-image-tile"]::attr(src)'
            ).getall()
            item["images"] = [
                img.replace("_SY88", "_SL1500").replace("_CR0,0,88,88", "")
                for img in images
            ]

            # Variant
            variant_text = review_el.css(
                "a.a-size-mini.a-link-normal.a-color-secondary::text"
            ).get("")
            if not variant_text:
                variant_text = review_el.css(
                    '[data-hook="format-strip"]::text'
                ).get("")
            item["variant"] = variant_text.strip()

            # Review URL
            review_link = review_el.css(
                'a[data-hook="review-title"]::attr(href)'
            ).get("")
            if review_link:
                item["review_url"] = response.urljoin(review_link)
            else:
                item["review_url"] = response.url

            yield item
            self._reviews_scraped += 1

    # ------------------------------------------------------------------
    # Stats
    # ------------------------------------------------------------------

    def closed(self, reason):
        """Log final scrape statistics."""
        self.logger.info(
            f"Spider stats: products_processed={self._products_processed}, "
            f"reviews_scraped={self._reviews_scraped}, "
            f"captcha_skipped={self._captcha_skipped}, "
            f"failed={self.items_failed}"
        )
