# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_cycle', models.CharField(blank=True, max_length=20)),
                ('next_renewal', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_intel"."subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ParsedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='whydud_email', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('marketplace', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=1000)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=500)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('match_status', models.CharField(default='pending', max_length=20)),
                ('email_message_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_intel"."parsed_orders',
                'unique_together': {('user', 'email_message_id')},
            },
        ),
        migrations.CreateModel(
            name='RefundTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('expected_by', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=50)),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_intel.parsedorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_intel"."refund_tracking',
            },
        ),
        migrations.CreateModel(
            name='ReturnWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_end_date', models.DateField()),
                ('is_extended', models.BooleanField(default=False)),
                ('alert_sent_3day', models.BooleanField(default=False)),
                ('alert_sent_1day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_intel.parsedorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_intel"."return_windows',
            },
        ),
        migrations.CreateModel(
            name='InboxEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('sender_address', models.EmailField(max_length=320)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('received_at', models.DateTimeField()),
                ('body_text_encrypted', models.BinaryField(blank=True, null=True)),
                ('body_html_encrypted', models.BinaryField(blank=True, null=True)),
                ('raw_size_bytes', models.IntegerField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('order', 'Order'), ('shipping', 'Shipping'), ('refund', 'Refund'), ('return', 'Return'), ('subscription', 'Subscription'), ('promo', 'Promotional'), ('other', 'Other')], max_length=30)),
                ('marketplace', models.CharField(blank=True, max_length=50)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('parsed_entity_type', models.CharField(blank=True, max_length=30)),
                ('parsed_entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_emails', to=settings.AUTH_USER_MODEL)),
                ('whydud_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.whydudemail')),
            ],
            options={
                'db_table': 'email_intel"."inbox_emails',
                'indexes': [models.Index(fields=['user', '-received_at'], name='inbox_email_user_id_d13d12_idx')],
            },
        ),
    ]
