# Generated by Django 5.2.11 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxemail',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10),
        ),
        migrations.AddField(
            model_name='inboxemail',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='inboxemail',
            name='resend_message_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
