# Generated by Django 5.2.11 on 2026-02-24 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_whydudemail_domain_alter_whydudemail_username_and_more'),
        ('email_intel', '0002_inboxemail_direction_inboxemail_recipient_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('whydud', 'Whydud'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('forwarding', 'Forwarding')], max_length=20)),
                ('email_address', models.CharField(max_length=320)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, max_length=500)),
                ('emails_synced', models.IntegerField(default=0)),
                ('orders_detected', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.oauthconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sources', to=settings.AUTH_USER_MODEL)),
                ('whydud_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.whydudemail')),
            ],
            options={
                'db_table': 'email_intel"."email_sources',
                'unique_together': {('user', 'email_address')},
            },
        ),
    ]
