# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Create all custom PostgreSQL schemas before any tables
        migrations.RunSQL(
            sql="""
                CREATE SCHEMA IF NOT EXISTS users;
                CREATE SCHEMA IF NOT EXISTS email_intel;
                CREATE SCHEMA IF NOT EXISTS scoring;
                CREATE SCHEMA IF NOT EXISTS tco;
                CREATE SCHEMA IF NOT EXISTS community;
            """,
            reverse_sql="""
                DROP SCHEMA IF EXISTS community CASCADE;
                DROP SCHEMA IF EXISTS tco CASCADE;
                DROP SCHEMA IF EXISTS scoring CASCADE;
                DROP SCHEMA IF EXISTS email_intel CASCADE;
                DROP SCHEMA IF EXISTS users CASCADE;
            """,
        ),
        migrations.CreateModel(
            name='ReservedUsername',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users"."reserved_usernames',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('registered', 'Registered'), ('connected', 'Connected'), ('premium', 'Premium'), ('moderator', 'Moderator'), ('senior_moderator', 'Senior Moderator'), ('data_ops', 'Data Ops'), ('fraud_analyst', 'Fraud Analyst'), ('trust_engineer', 'Trust Engineer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='registered', max_length=30)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('has_whydud_email', models.BooleanField(default=False)),
                ('trust_score', models.DecimalField(decimal_places=2, default='0.50', max_digits=3)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users"."accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('membership', 'Membership')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('card_variant', models.CharField(blank=True, max_length=200)),
                ('card_network', models.CharField(blank=True, max_length=20)),
                ('wallet_provider', models.CharField(blank=True, max_length=50)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upi_app', models.CharField(blank=True, max_length=50)),
                ('upi_bank', models.CharField(blank=True, max_length=100)),
                ('membership_type', models.CharField(blank=True, max_length=50)),
                ('emi_eligible', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."payment_methods',
            },
        ),
        migrations.CreateModel(
            name='WhydudEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_emails_received', models.IntegerField(default=0)),
                ('total_orders_detected', models.IntegerField(default=0)),
                ('last_email_received_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('marketplaces_registered', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whydud_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."whydud_emails',
            },
        ),
        migrations.CreateModel(
            name='OAuthConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_user_id', models.CharField(max_length=200)),
                ('access_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('refresh_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."oauth_connections',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
