# Generated by Django 5.2.11 on 2026-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_reserved_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='whydudemail',
            name='domain',
            field=models.CharField(choices=[('whyd.in', 'whyd.in'), ('whyd.click', 'whyd.click'), ('whyd.shop', 'whyd.shop')], default='whyd.in', max_length=20),
        ),
        migrations.AlterField(
            model_name='whydudemail',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='whydudemail',
            unique_together={('username', 'domain')},
        ),
    ]
