# Generated by Django 5.2.11 on 2026-02-24 17:33

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_whydudemail_domain_alter_whydudemail_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_drops', models.JSONField(default=apps.accounts.models._pref_in_app_and_email)),
                ('return_windows', models.JSONField(default=apps.accounts.models._pref_in_app_and_email)),
                ('refund_delays', models.JSONField(default=apps.accounts.models._pref_in_app_and_email)),
                ('back_in_stock', models.JSONField(default=apps.accounts.models._pref_in_app_only)),
                ('review_upvotes', models.JSONField(default=apps.accounts.models._pref_in_app_only)),
                ('price_alerts', models.JSONField(default=apps.accounts.models._pref_in_app_and_email)),
                ('discussion_replies', models.JSONField(default=apps.accounts.models._pref_in_app_only)),
                ('level_up', models.JSONField(default=apps.accounts.models._pref_in_app_only)),
                ('points_earned', models.JSONField(default=apps.accounts.models._pref_in_app_only)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('price_drop', 'Price Drop'), ('return_window', 'Return Window'), ('refund_delay', 'Refund Delay'), ('back_in_stock', 'Back in Stock'), ('review_upvote', 'Review Upvote'), ('price_alert', 'Price Alert'), ('discussion_reply', 'Discussion Reply'), ('level_up', 'Level Up'), ('points_earned', 'Points Earned'), ('subscription_renewal', 'Subscription Renewal')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."notifications',
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(condition=models.Q(('is_read', False)), fields=['user', 'is_read'], name='idx_notif_unread')],
            },
        ),
    ]
