# Generated by Django 5.2.11 on 2026-02-24 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificationpreference_notification'),
        ('products', '0004_categorypreferenceschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferences', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."purchase_preferences',
                'indexes': [models.Index(fields=['user'], name='purchase_pr_user_id_b2f9a6_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
