# Generated by Django 5.2.11 on 2026-02-26 15:55

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_referral_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.accounts.models._generate_referral_code, max_length=8, unique=True),
        ),
    ]
