# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('electricity_tariff_residential', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cooling_days_per_year', models.IntegerField(blank=True, null=True)),
                ('humidity_level', models.CharField(blank=True, max_length=20)),
                ('water_tariff_per_kl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('water_hardness', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tco"."city_reference_data',
                'unique_together': {('city_name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='UserTCOProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electricity_tariff_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ac_hours_per_day', models.SmallIntegerField(blank=True, null=True)),
                ('ownership_years', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tco.cityreferencedata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tco_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."tco_profiles',
            },
        ),
        migrations.CreateModel(
            name='TCOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('input_schema', models.JSONField()),
                ('cost_components', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_models', to='products.category')),
            ],
            options={
                'db_table': 'tco"."models',
                'unique_together': {('category', 'version')},
            },
        ),
    ]
