# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_review_id', models.CharField(blank=True, max_length=200)),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('rating', models.SmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('extracted_pros', models.JSONField(default=list)),
                ('extracted_cons', models.JSONField(default=list)),
                ('credibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fraud_flags', models.JSONField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('vote_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.productlisting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."review_votes',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='reviews_product_3516b2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_hash'], name='reviews_content_093cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('listing', 'external_review_id')},
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.CheckConstraint(condition=models.Q(('vote__in', [1, -1])), name='vote_value'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('review', 'user')},
        ),
    ]
