# Generated by Django 5.2.11 on 2026-02-24 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_body_negative_review_body_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_upvotes_received', models.IntegerField(default=0)),
                ('total_helpful_votes', models.IntegerField(default=0)),
                ('review_quality_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviewer_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('leaderboard_rank', models.IntegerField(blank=True, null=True)),
                ('is_top_reviewer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users"."reviewer_profiles',
            },
        ),
    ]
