# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_type', models.CharField(choices=[('error_price', 'Error Pricing'), ('lowest_ever', 'Lowest Ever'), ('genuine_discount', 'Genuine Discount'), ('flash_sale', 'Flash Sale')], max_length=30)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productlisting')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='products.product')),
            ],
            options={
                'db_table': 'deals',
                'indexes': [models.Index(fields=['is_active', 'deal_type'], name='deals_is_acti_65d32b_idx')],
            },
        ),
    ]
