# Generated by Django 5.2.11 on 2026-02-22 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('verified', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('affiliate_tag', models.CharField(blank=True, max_length=100)),
                ('affiliate_param', models.CharField(blank=True, max_length=50)),
                ('scraper_status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplaces',
            },
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_slug', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('card_variant', models.CharField(max_length=200)),
                ('card_type', models.CharField(max_length=20)),
                ('card_network', models.CharField(blank=True, max_length=20)),
                ('is_co_branded', models.BooleanField(default=False)),
                ('co_brand_partner', models.CharField(blank=True, max_length=50)),
                ('default_cashback_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'bank_cards',
                'unique_together': {('bank_slug', 'card_variant', 'card_type')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('spec_schema', models.JSONField(blank=True, null=True)),
                ('level', models.SmallIntegerField(default=0)),
                ('has_tco_model', models.BooleanField(default=False)),
                ('product_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('dud_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dud_score_confidence', models.CharField(blank=True, max_length=20)),
                ('dud_score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('lowest_price_ever', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lowest_price_date', models.DateField(blank=True, null=True)),
                ('current_best_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_best_marketplace', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('is_refurbished', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='products.product')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_seller_id', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_ratings', models.IntegerField(default=0)),
                ('positive_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ships_from', models.CharField(blank=True, max_length=200)),
                ('fulfilled_by', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('seller_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='products.marketplace')),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200)),
                ('external_url', models.URLField(max_length=2000)),
                ('affiliate_url', models.URLField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.seller')),
            ],
            options={
                'db_table': 'product_listings',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_i_0d1950_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-dud_score'], name='products_dud_sco_d9b7fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('marketplace', 'external_seller_id')},
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['product'], name='product_lis_product_570215_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('marketplace', 'external_id')},
        ),
    ]
