# Generated by Django 5.2.11 on 2026-02-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comparesession_recentlyviewed_stockalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPreferenceSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_schema', to='products.category')),
            ],
            options={
                'db_table': 'category_preference_schemas',
            },
        ),
    ]
