# Generated by Django 5.2.11 on 2026-03-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorypreferenceschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MarketplaceCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_category_path', models.CharField(help_text="Full breadcrumb path as scraped, e.g. 'Electronics > Audio > Headphones'", max_length=1000)),
                ('marketplace_category_slug', models.SlugField(help_text="Slugified version of marketplace's leaf category", max_length=300)),
                ('confidence', models.CharField(choices=[('manual', 'Manual — admin verified'), ('auto', 'Auto — mapped by rules'), ('unreviewed', 'Unreviewed — needs admin check')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='products.category')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='products.marketplace')),
            ],
            options={
                'db_table': 'marketplace_category_mappings',
                'indexes': [models.Index(fields=['marketplace', 'marketplace_category_slug'], name='marketplace_marketp_b3d190_idx')],
                'unique_together': {('marketplace', 'marketplace_category_slug')},
            },
        ),
    ]
