# Generated by Django 5.2.11 on 2026-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_hierarchy_marketplace_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_lightweight',
            field=models.BooleanField(db_index=True, default=False, help_text='True if created from tracker data only (no marketplace scrape yet)'),
        ),
    ]
